package com.keystone.deliveryservice.ENUM;

public enum NotificationType {
    WORK_ORDER_CREATED,
    WORK_ORDER_ASSIGNED,
    TECHNICIAN_ASSIGNMENT,
    WORK_ORDER_STATUS,
    WORK_ORDER_COMPLETED,
    CRITICAL_WORK_ORDER,
    PAYMENT_PENDING,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,
    EMAIL_VERIFIED,
    SECURITY,
    CUSTOMER_REGISTERED,
    ATTENDANCE
}
