 package com.keystone.deliveryservice.ENUM;

public enum Permissions{

	CREATE_USER,UPDATE_USER,DELETE_USER,VIEW_USER,
	
	CREATE_CUSTOMER,UPTDATE_CUSTOMER,DELETE_CUSTOMER,VIEW_CUSTOMER,
	
	CREATE_SITE,UPTDATE_SITE,DELETE_SITE,VIEW_SITE,
	
	CREATE_WORK_ORDER,UPTDATE_WORK_ORDER,DELETE_WORK_ORDER,VIEW_WORK_ORDER,ASSIN_WORK_ORDER,CLOSE_WORK_ORDER,CANCEL_WORK_ORDER,
	
	START_WORK,HOLD_WORK,RESUME_WORK,COMPLETE_WORK,
	
	RAISE_REQUEST,VIEW_OWN_REQUEST,
	
	ADD_PARTS,UPDATE_PARTS,DELETE_PARTS,VIEW_PARTS,USE_PARTS,
	
	ADD_TIME_LOGS,VIEW_TIME_LOGS,
	
	SEND_NOTIFICATION,
	VIEW_DASHBOARD,VIEW_REPORTS,
	
}
